<?php


$form	= array(
		'preset'		=> array(
				'id'			=> 'preset',
				'order'			=> 10,
				'type'			=> 'dropdown',
				'value'			=> array(),
				'validation'	=> '',
				'options'		=> array(),
				'label'			=> 'themer.client.themer.form.label.preset',
				'description'	=> 'themer.client.themer.form.description.preset',
		),
		'assets' => array(
				'id' => 'assets',
				'type' => 'hidden',
				'value' => null,
				'nodesc' => true,
				),
		'fullwidth' => array(
				'id' => 'fullwidth',
				'type' => 'hidden',
				'value' => null,
				'nodesc' => true,
				),
		'contentbg'	=> array(
				'order'			=> 18,
				'type'			=> 'minicolors',
				'value'			=> '#FFFFFF',
				'label'			=> 'themer.admin.themer.form.theme.label.contentbg',
				'description'	=> 'themer.admin.themer.form.theme.description.contentbg',
				'onchange'		=> 'javascript:updateCss(\'contentbg\', this.value);',
				'style'			=> 'width: 75px;'
		),
		
		'bodytype' => array(
				'order'			=> 20,
				'type'			=> 'togglebtn',
				'value'			=> array( '1' ),
				'validation'	=> '',
				'class'			=> 'btn-mini',
				'options'		=> array(
						array( 'id' => '1', 'name' => 'themer.admin.themer.form.theme.bodytype.optn.solid' ),
						array( 'id' => '2', 'name' => 'themer.admin.themer.form.theme.bodytype.optn.gradient' ),
						array( 'id' => '3', 'name' => 'themer.admin.themer.form.theme.bodytype.optn.pattern' ),
						array( 'id' => '4', 'name' => 'themer.admin.themer.form.theme.bodytype.optn.image' )
				),
				'label'			=> 'themer.admin.themer.form.theme.label.bodytype',
				'onclick'		=> 'javascript:updateCss(\'bodytype\', this.value)',
				'description'	=> 'themer.admin.themer.form.theme.description.bodytype',
		),
		'bodytypeoptn1'	=> array( 'order'	=> 21, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'bodyoptnsolid' => array(
				'id'			=> 'bodyoptnsolid',
				'order'			=> 25,
				'type'			=> 'minicolors',
				'value'			=> '#EFEFEF',
				'label'			=> 'themer.admin.themer.form.theme.label.bodyoptnsolid',
				'description'	=> 'themer.admin.themer.form.theme.description.bodyoptnsolid',
				'onchange'		=> 'javascript:updateCss(\'bodyoptnsolid\', this.value);',
				'style'			=> 'width: 75px;'
		),
		'bodytypeoptn1c'	=> array( 'order'	=> 26, 'type'	=> 'wrapc' ),
		'bodytypeoptn2'	=> array( 'order'	=> 31, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'bodyoptnfrom' => array(
				'order'			=> 33,
				'type'			=> 'minicolors',
				'value'			=> '#EFEFEF',
				'nodesc'		=> true,
				'label'			=> 'themer.admin.themer.form.theme.label.bodyoptnfrom',
				'description'	=> 'themer.admin.themer.form.theme.description.bodyoptnfrom',
				'onchange'		=> 'javascript:updateCss(\'bodyoptnfrom\', this.value);',
				'style'			=> 'width: 75px;'
		),
		'bodyoptnto' => array(
				'order'			=> 35,
				'type'			=> 'minicolors',
				'value'			=> '#EFEFEF',
				'nodesc'		=> true,
				'label'			=> 'themer.admin.themer.form.theme.label.bodyoptnto',
				'description'	=> 'themer.admin.themer.form.theme.description.bodyoptnto',
				'onchange'		=> 'javascript:updateCss(\'bodyoptnto\', this.value);',
				'style'			=> 'width: 75px;'
		),
		'bodyoptndir' => array(
				'order'			=> 37,
				'type'			=> 'dropdown',
				'options'		=> array(
						array( 'id' => '1', 'name' => 'themer.admin.themer.form.theme.bodyoptndir.optn.vert' ),
						array( 'id' => '2', 'name' => 'themer.admin.themer.form.theme.bodyoptndir.optn.horiz' ),
						array( 'id' => '3', 'name' => 'themer.admin.themer.form.theme.bodyoptndir.optn.diagl' ),
						array( 'id' => '4', 'name' => 'themer.admin.themer.form.theme.bodyoptndir.optn.diagr' ),
						array( 'id' => '5', 'name' => 'themer.admin.themer.form.theme.bodyoptndir.optn.rad' ),
				),
				'label'			=> 'themer.admin.themer.form.theme.label.bodyoptndir',
				'description'	=> 'themer.admin.themer.form.theme.description.bodyoptndir',
				'onchange'		=> 'javascript:updateCss(\'bodyoptndir\', this.value);'
		),
		'bodytypeoptn2c'	=> array( 'order'	=> 39, 'type'	=> 'wrapc' ),
		'bodytypeoptn3'	=> array( 'order'	=> 41, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'bodyoptnpattern' => array(
				'order'			=> 45,
				'type'			=> 'pattern',
				'value'			=> '',
				'label'			=> 'themer.admin.themer.form.theme.label.bodyoptnpattern',
				'description'	=> 'themer.admin.themer.form.theme.description.bodyoptnpattern',
				'onchange'		=> 'javascript:updateCss(\'bodyoptnpattern\', this.value);'
		),
		'bodytypeoptn3c'	=> array( 'order'	=> 46, 'type'	=> 'wrapc' ),
		'bodytypeoptn4'	=> array( 'order'	=> 51, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'bodyoptnimage' => array(
				'order'			=> 55,
				'type'			=> 'text',
				'value'			=> '',
				'label'			=> 'themer.admin.themer.form.theme.label.bodyoptnimage',
				'description'	=> 'themer.admin.themer.form.theme.description.bodyoptnimage',
				'onchange'		=> 'javascript:updateCss(\'bodyoptnimage\', this.value);'
		),
		'bodytypeoptn4c'	=> array( 'order'	=> 56, 'type'	=> 'wrapc' ),
		'alinks' => array(
				'order'			=> 100,
				'type'			=> 'togglebtn',
				'value'			=> array( '1' ),
				'validation'	=> '',
				'options'		=> array(
						array( 'id' => '1', 'name' => 'themer.client.themer.form.theme.alinks.optn.std' ),
						array( 'id' => '2', 'name' => 'themer.client.themer.form.theme.alinks.optn.vis' ),
						array( 'id' => '3', 'name' => 'themer.client.themer.form.theme.alinks.optn.hov' )
				),
				'label'			=> 'themer.admin.themer.form.theme.label.alinks',
				'class'			=> 'btn-mini',
				'description'	=> 'themer.client.themer.form.theme.description.alinks',
		),
		'alinksoptn1'	=> array( 'order'	=> 101, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'alinksstd' => array(
				'order'			=> 105,
				'type'			=> 'minicolors',
				'value'			=> '#004A95',
				'label'			=> 'themer.admin.themer.form.theme.label.alinksstd',
				'description'	=> 'themer.admin.themer.form.theme.description.alinksstd',
				'onchange'		=> 'javascript:updateCss(\'alinksstd\', this.value);',
				'style'			=> 'width: 75px;'
		),
		'alinksoptn1c'	=> array( 'order'	=> 26, 'type'	=> 'wrapc' ),
		'alinksoptn2'	=> array( 'order'	=> 111, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'alinksvis' => array(
				'order'			=> 115,
				'type'			=> 'minicolors',
				'value'			=> '#004A95',
				'label'			=> 'themer.admin.themer.form.theme.label.alinksvis',
				'description'	=> 'themer.admin.themer.form.theme.description.alinksvis',
				'onchange'		=> 'javascript:updateCss(\'alinksvis\', this.value);',
				'style'			=> 'width: 75px;'
		),
		'alinksoptn2c'	=> array( 'order'	=> 119, 'type'	=> 'wrapc' ),
		'alinksoptn3'	=> array( 'order'	=> 121, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'alinkshov' => array(
				'order'			=> 125,
				'type'			=> 'minicolors',
				'value'			=> '#005580',
				'label'			=> 'themer.admin.themer.form.theme.label.alinkshov',
				'description'	=> 'themer.admin.themer.form.theme.description.alinkshov',
				'onchange'		=> 'javascript:updateCss(\'alinkshov\', this.value);',
				'style'			=> 'width: 75px;'
		),
		'alinksoptn3c'	=> array( 'order'	=> 129, 'type'	=> 'wrapc' ),
		
		'navbar'		=> array(
				'order'			=> 150,
				'type'			=> 'togglebtn',
				'value'			=> array( '1' ),
				'validation'	=> '',
				'options'		=> array(
						array( 'id' => '1', 'name' => 'themer.admin.themer.form.theme.navbar.optn.main' ),
						array( 'id' => '2', 'name' => 'themer.admin.themer.form.theme.navbar.optn.drop' )
				),
				'label'			=> 'themer.admin.themer.form.theme.label.navbar',
				'class'			=> 'btn-mini',
		),
		'navbaroptn1'		=> array( 'order'	=> 151, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'navbarfrom' => array(
				'order'			=> 152,
				'type'			=> 'minicolors',
				'value'			=> '#333333',
				'nodesc'		=> true,
				'style'			=> 'width: 75px;',
				'label'			=> 'themer.admin.themer.form.theme.label.navbarfrom',
				'onchange'		=> 'javascript:updateCss(\'navbarfrom\', this.value);',
		),
		'navbarto' => array(
				'order'			=> 154,
				'type'			=> 'minicolors',
				'value'			=> '#222222',
				'nodesc'		=> true,
				'style'			=> 'width: 75px;',
				'label'			=> 'themer.admin.themer.form.theme.label.navbarto',
				'onchange'		=> 'javascript:updateCss(\'navbarto\', this.value);',
		),
		'navbartxt' => array(
				'order'			=> 156,
				'type'			=> 'minicolors',
				'value'			=> '#999999',
				'nodesc'		=> true,
				'style'			=> 'width: 75px;',
				'label'			=> 'themer.admin.themer.form.theme.label.navbartxt',
				'onchange'		=> 'javascript:updateCss(\'navbartxt\', this.value);',
		),
		'navbarhov' => array(
				'order'			=> 158,
				'type'			=> 'minicolors',
				'value'			=> '#999999',
				'nodesc'		=> true,
				'style'			=> 'width: 75px;',
				'label'			=> 'themer.admin.themer.form.theme.label.navbarhov',
				'onchange'		=> 'javascript:updateCss(\'navbarhov\', this.value);',
		),
		'navbaroptn1c	'	=> array( 'order'	=> 159, 'type'	=> 'wrapc' ),
		'navbaroptn2'		=> array( 'order'	=> 161, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'navbardropbg' => array(
				'order'			=> 162,
				'type'			=> 'minicolors',
				'value'			=> '#ffffff',
				'nodesc'		=> true,
				'style'			=> 'width: 75px;',
				'label'			=> 'themer.admin.themer.form.theme.label.navbardropbg',
				'onchange'		=> 'javascript:updateCss(\'navbardropbg\', this.value);',
		),
		'navbardroptxt' => array(
				'order'			=> 164,
				'type'			=> 'minicolors',
				'value'			=> '#333333',
				'nodesc'		=> true,
				'style'			=> 'width: 75px;',
				'label'			=> 'themer.admin.themer.form.theme.label.navbardroptxt',
				'onchange'		=> 'javascript:updateCss(\'navbardroptxt\', this.value);',
		),
		'navbardrophl' => array(
				'order'			=> 166,
				'type'			=> 'minicolors',
				'value'			=> '#0088cc',
				'nodesc'		=> true,
				'style'			=> 'width: 75px;',
				'label'			=> 'themer.admin.themer.form.theme.label.navbardrophl',
				'onchange'		=> 'javascript:updateCss(\'navbardrophl\', this.value);',
		),
		'navbaroptn2c	'	=> array( 'order'	=> 169, 'type'	=> 'wrapc' ),
		
		'txtelem'		=> array(
				'order'			=> 200,
				'type'			=> 'togglebtn',
				'value'			=> array( '1' ),
				'validation'	=> '',
				'options'		=> array(
						array( 'id' => '1', 'name' => 'themer.admin.themer.form.theme.txtelem.optn.gf' ),
						array( 'id' => '2', 'name' => 'themer.admin.themer.form.theme.txtelem.optn.h1' ),
						array( 'id' => '3', 'name' => 'themer.admin.themer.form.theme.txtelem.optn.h2' ),
						array( 'id' => '4', 'name' => 'themer.admin.themer.form.theme.txtelem.optn.h3' ),
						array( 'id' => '5', 'name' => 'themer.admin.themer.form.theme.txtelem.optn.h4' ),
						array( 'id' => '6', 'name' => 'themer.admin.themer.form.theme.txtelem.optn.h5' ),
						array( 'id' => '7', 'name' => 'themer.admin.themer.form.theme.txtelem.optn.h6' ),
				),
				'label'			=> 'themer.admin.themer.form.theme.label.textelem',
				'class'			=> 'btn-mini',
		),
		'txtelemoptn1'		=> array( 'order'	=> 210, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'txtelemgfcolor' => array(
				'order'			=> 216,
				'type'			=> 'minicolors',
				'value'			=> '#333333',
				'nodesc'		=> true,
				'label'			=> 'themer.admin.themer.form.theme.label.txtelemgfcolor',
				'onchange'		=> 'javascript:updateCss(\'txtelemgfcolor\', this.value);',
				'style'			=> 'width: 75px;',
		),
		'txtelemoptn1c'		=> array( 'order'	=> 219, 'class'	=> 'well well-small', 'type'	=> 'wrapc' ),
		'txtelemoptn2'		=> array( 'order'	=> 220, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'txtelemh1color' => array(
				'order'			=> 226,
				'type'			=> 'minicolors',
				'value'			=> '#333333',
				'nodesc'		=> true,
				'label'			=> 'themer.admin.themer.form.theme.label.txtelemgfcolor',
				'onchange'		=> 'javascript:updateCss(\'txtelemh1color\', this.value);',
				'style'			=> 'width: 75px;',
		),
		'txtelemoptn2c'		=> array( 'order'	=> 229, 'class'	=> 'well well-small', 'type'	=> 'wrapc' ),
		'txtelemoptn3'		=> array( 'order'	=> 230, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'txtelemh2color' => array(
				'order'			=> 236,
				'type'			=> 'minicolors',
				'value'			=> '#333333',
				'nodesc'		=> true,
				'label'			=> 'themer.admin.themer.form.theme.label.txtelemgfcolor',
				'onchange'		=> 'javascript:updateCss(\'txtelemh2color\', this.value);',
				'style'			=> 'width: 75px;',
		),
		'txtelemoptn3c'		=> array( 'order'	=> 239, 'class'	=> 'well well-small', 'type'	=> 'wrapc' ),
		'txtelemoptn4'		=> array( 'order'	=> 240, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'txtelemh3color' => array(
				'order'			=> 246,
				'type'			=> 'minicolors',
				'value'			=> '#333333',
				'nodesc'		=> true,
				'label'			=> 'themer.admin.themer.form.theme.label.txtelemgfcolor',
				'onchange'		=> 'javascript:updateCss(\'txtelemh3color\', this.value);',
				'style'			=> 'width: 75px;',
		),
		'txtelemoptn4c'		=> array( 'order'	=> 249, 'class'	=> 'well well-small', 'type'	=> 'wrapc' ),
		'txtelemoptn5'		=> array( 'order'	=> 250, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'txtelemh4color' => array(
				'order'			=> 256,
				'type'			=> 'minicolors',
				'value'			=> '#333333',
				'nodesc'		=> true,
				'label'			=> 'themer.admin.themer.form.theme.label.txtelemgfcolor',
				'onchange'		=> 'javascript:updateCss(\'txtelemh4color\', this.value);',
				'style'			=> 'width: 75px;',
		),
		'txtelemoptn5c'		=> array( 'order'	=> 259, 'class'	=> 'well well-small', 'type'	=> 'wrapc' ),
		'txtelemoptn6'		=> array( 'order'	=> 260, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'txtelemh5color' => array(
				'order'			=> 266,
				'type'			=> 'minicolors',
				'value'			=> '#333333',
				'nodesc'		=> true,
				'label'			=> 'themer.admin.themer.form.theme.label.txtelemgfcolor',
				'onchange'		=> 'javascript:updateCss(\'txtelemh5color\', this.value);',
				'style'			=> 'width: 75px;',
		),
		'txtelemoptn6c'		=> array( 'order'	=> 269, 'class'	=> 'well well-small', 'type'	=> 'wrapc' ),
		'txtelemoptn7'		=> array( 'order'	=> 270, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'txtelemh6color' => array(
				'order'			=> 276,
				'type'			=> 'minicolors',
				'value'			=> '#999999',
				'nodesc'		=> true,
				'label'			=> 'themer.admin.themer.form.theme.label.txtelemgfcolor',
				'onchange'		=> 'javascript:updateCss(\'txtelemh6color\', this.value);',
				'style'			=> 'width: 75px;',
		),
		'txtelemoptn7c'		=> array( 'order'	=> 279, 'class'	=> 'well well-small', 'type'	=> 'wrapc' ),
		
);
