<?php


$form	= array(
		'name'		=> array(
				'order'			=> 10,
				'type'			=> 'text',
				'value'			=> '',
				'validation'	=> '',
				'label'			=> 'themer.admin.themer.form.theme.label.name',
				'description'	=> 'themer.admin.themer.form.theme.description.name',
				),
		'description'		=> array(
				'order'			=> 11,
				'type'			=> 'text',
				'value'			=> '',
				'validation'	=> '',
				'nodesc'		=> true,
				'class'			=> 'span10',
				'label'			=> 'themer.admin.themer.form.theme.label.description',
				),
		'fullwidth' => array(
				'order'			=> 12,
				'type'			=> 'toggleyn',
				'value'			=> false,
				'validation'	=> '',
				'labelon'		=> 'themer.form.toggleyn.enabled',
				'labeloff'		=> 'themer.form.toggleyn.disabled',
				'label'			=> 'themer.admin.themer.form.theme.label.fullwidth',
				'description'	=> 'themer.admin.themer.form.theme.description.fullwidth',
				),
		'font' => array(
				'order' => 15,
				'type' => 'webfont',
				'value' => '"Helvetica Neue"',
				'validation' => '',
				'label' => 'themer.admin.themer.form.theme.label.font',
				'description' => 'themer.admin.themer.form.theme.description.font',
				'primary' => true,
				),
		'logo'		=> array(
				'order'			=> 17,
				'id'			=> 'mylogo',
				'type'			=> 'text',
				'value'			=> get_baseurl( 'client' ) . 'templates/default/img/whmcslogo.png',
				'validation'	=> '',
				'label'			=> 'themer.admin.themer.form.theme.label.logo',
				'description'	=> 'themer.admin.themer.form.theme.description.logo',
		),
		'contentbg'	=> array(
				'order'			=> 18,
				'type'			=> 'minicolors',
				'value'			=> '#FFFFFF',
				'label'			=> 'themer.admin.themer.form.theme.label.contentbg',
				'description'	=> 'themer.admin.themer.form.theme.description.contentbg',
				),
		'bodytype' => array(
				'order'			=> 20,
				'type'			=> 'togglebtn',
				'value'			=> array( '1' ),
				'validation'	=> '',
				'options'		=> array( 
						array( 'id' => '1', 'name' => 'themer.admin.themer.form.theme.bodytype.optn.solid' ), 
						array( 'id' => '2', 'name' => 'themer.admin.themer.form.theme.bodytype.optn.gradient' ),
						array( 'id' => '3', 'name' => 'themer.admin.themer.form.theme.bodytype.optn.pattern' ),
						array( 'id' => '4', 'name' => 'themer.admin.themer.form.theme.bodytype.optn.image' )
						),
				'label'			=> 'themer.admin.themer.form.theme.label.bodytype',
				//'description'	=> 'themer.admin.themer.form.theme.description.bodytype',
				//'onclick'		=> 'javascript:typechanger( \'body\', this.value, this );',
				),
		'bodytypeoptn1'	=> array( 'order'	=> 21, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
			'bodyoptnsolid' => array(
					'order'			=> 25,
					'type'			=> 'minicolors',
					'value'			=> '#EFEFEF',
					'label'			=> 'themer.admin.themer.form.theme.label.bodyoptnsolid',
					'description'	=> 'themer.admin.themer.form.theme.description.bodyoptnsolid',
					),
		'bodytypeoptn1c'	=> array( 'order'	=> 26, 'type'	=> 'wrapc' ),
		'bodytypeoptn2'	=> array( 'order'	=> 31, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
			'bodyoptnfrom' => array(
					'order'			=> 33,
					'type'			=> 'minicolors',
					'value'			=> '#EFEFEF',
					'nodesc'		=> true,
					'label'			=> 'themer.admin.themer.form.theme.label.bodyoptnfrom',
					'description'	=> 'themer.admin.themer.form.theme.description.bodyoptnfrom',
			),
			'bodyoptnto' => array(
					'order'			=> 35,
					'type'			=> 'minicolors',
					'value'			=> '#EFEFEF',
					'nodesc'		=> true,
					'label'			=> 'themer.admin.themer.form.theme.label.bodyoptnto',
					'description'	=> 'themer.admin.themer.form.theme.description.bodyoptnto',
			),
			'bodyoptndir' => array(
					'order'			=> 37,
					'type'			=> 'dropdown',
					'options'		=> array( 
						array( 'id' => '1', 'name' => 'themer.admin.themer.form.theme.bodyoptndir.optn.vert' ), 
						array( 'id' => '2', 'name' => 'themer.admin.themer.form.theme.bodyoptndir.optn.horiz' ),
						array( 'id' => '3', 'name' => 'themer.admin.themer.form.theme.bodyoptndir.optn.diagl' ),
						array( 'id' => '4', 'name' => 'themer.admin.themer.form.theme.bodyoptndir.optn.diagr' ),
						array( 'id' => '5', 'name' => 'themer.admin.themer.form.theme.bodyoptndir.optn.rad' ),
						),
					'label'			=> 'themer.admin.themer.form.theme.label.bodyoptndir',
					'description'	=> 'themer.admin.themer.form.theme.description.bodyoptndir',
			),
		'bodytypeoptn2c'	=> array( 'order'	=> 39, 'type'	=> 'wrapc' ),
		'bodytypeoptn3'	=> array( 'order'	=> 41, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
			'bodyoptnpattern' => array(
					'order'			=> 45,
					'type'			=> 'pattern',
					'value'			=> '',
					'label'			=> 'themer.admin.themer.form.theme.label.bodyoptnpattern',
					'description'	=> 'themer.admin.themer.form.theme.description.bodyoptnpattern',
			),
		'bodytypeoptn3c'	=> array( 'order'	=> 46, 'type'	=> 'wrapc' ),
		'bodytypeoptn4'	=> array( 'order'	=> 51, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
			'bodyoptnimage' => array(
					'order'			=> 55,
					'type'			=> 'text',
					'value'			=> '',
					'label'			=> 'themer.admin.themer.form.theme.label.bodyoptnimage',
					'description'	=> 'themer.admin.themer.form.theme.description.bodyoptnimage',
			),
		'bodytypeoptn4c'	=> array( 'order'	=> 56, 'type'	=> 'wrapc' ),
		
		'alinks' => array(
				'order'			=> 100,
				'type'			=> 'togglebtn',
				'value'			=> array( '1' ),
				'validation'	=> '',
				'options'		=> array(
						array( 'id' => '1', 'name' => 'themer.admin.themer.form.theme.alinks.optn.std' ),
						array( 'id' => '2', 'name' => 'themer.admin.themer.form.theme.alinks.optn.vis' ),
						array( 'id' => '3', 'name' => 'themer.admin.themer.form.theme.alinks.optn.hov' )
				),
				'label'			=> 'themer.admin.themer.form.theme.label.alinks',
				//'onclick'		=> 'javascript:typechanger( \'body\', this.value, this );',
		),
		'alinksoptn1'	=> array( 'order'	=> 101, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'alinksstd' => array(
				'order'			=> 105,
				'type'			=> 'minicolors',
				'value'			=> '#004A95',
				'label'			=> 'themer.admin.themer.form.theme.label.alinksstd',
				'description'	=> 'themer.admin.themer.form.theme.description.alinksstd',
		),
		'alinksoptn1c'	=> array( 'order'	=> 26, 'type'	=> 'wrapc' ),
		'alinksoptn2'	=> array( 'order'	=> 111, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'alinksvis' => array(
				'order'			=> 115,
				'type'			=> 'minicolors',
				'value'			=> '#004A95',
				'label'			=> 'themer.admin.themer.form.theme.label.alinksvis',
				'description'	=> 'themer.admin.themer.form.theme.description.alinksvis',
		),
		'alinksoptn2c'	=> array( 'order'	=> 119, 'type'	=> 'wrapc' ),
		'alinksoptn3'	=> array( 'order'	=> 121, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'alinkshov' => array(
				'order'			=> 125,
				'type'			=> 'minicolors',
				'value'			=> '#005580',
				'label'			=> 'themer.admin.themer.form.theme.label.alinkshov',
				'description'	=> 'themer.admin.themer.form.theme.description.alinkshov',
		),
		'alinksoptn3c'	=> array( 'order'	=> 129, 'type'	=> 'wrapc' ),
		'navbar'		=> array(
				'order'			=> 150,
				'type'			=> 'togglebtn',
				'value'			=> array( '1' ),
				'validation'	=> '',
				'options'		=> array(
						array( 'id' => '1', 'name' => 'themer.admin.themer.form.theme.navbar.optn.main' ),
						array( 'id' => '2', 'name' => 'themer.admin.themer.form.theme.navbar.optn.drop' )
				),
				'label'			=> 'themer.admin.themer.form.theme.label.navbar',
				),
		'navbaroptn1'		=> array( 'order'	=> 151, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
			'navbarfrom' => array(
					'order'			=> 152,
					'type'			=> 'minicolors',
					'value'			=> '#333333',
					'nodesc'		=> true,
					'label'			=> 'themer.admin.themer.form.theme.label.navbarfrom',
			),
			'navbarto' => array(
					'order'			=> 154,
					'type'			=> 'minicolors',
					'value'			=> '#222222',
					'nodesc'		=> true,
					'label'			=> 'themer.admin.themer.form.theme.label.navbarto',
			),
			'navbartxt' => array(
					'order'			=> 156,
					'type'			=> 'minicolors',
					'value'			=> '#999999',
					'nodesc'		=> true,
					'label'			=> 'themer.admin.themer.form.theme.label.navbartxt',
			),
			'navbarhov' => array(
					'order'			=> 158,
					'type'			=> 'minicolors',
					'value'			=> '#999999',
					'nodesc'		=> true,
					'label'			=> 'themer.admin.themer.form.theme.label.navbarhov',
			),
		'navbaroptn1c	'	=> array( 'order'	=> 159, 'type'	=> 'wrapc' ),
		'navbaroptn2'		=> array( 'order'	=> 161, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
			'navbardropbg' => array(
					'order'			=> 162,
					'type'			=> 'minicolors',
					'value'			=> '#ffffff',
					'nodesc'		=> true,
					'label'			=> 'themer.admin.themer.form.theme.label.navbardropbg',
			),
			'navbardroptxt' => array(
					'order'			=> 164,
					'type'			=> 'minicolors',
					'value'			=> '#333333',
					'nodesc'		=> true,
					'label'			=> 'themer.admin.themer.form.theme.label.navbardroptxt',
			),
			'navbardrophl' => array(
					'order'			=> 166,
					'type'			=> 'minicolors',
					'value'			=> '#0088cc',
					'nodesc'		=> true,
					'label'			=> 'themer.admin.themer.form.theme.label.navbardrophl',
			),
		'navbaroptn2c	'	=> array( 'order'	=> 169, 'type'	=> 'wrapc' ),
		'txtelem'		=> array(
				'order'			=> 200,
				'type'			=> 'togglebtn',
				'value'			=> array( '1' ),
				'validation'	=> '',
				'options'		=> array(
						array( 'id' => '1', 'name' => 'themer.admin.themer.form.theme.txtelem.optn.gf' ),
						array( 'id' => '2', 'name' => 'themer.admin.themer.form.theme.txtelem.optn.h1' ),
						array( 'id' => '3', 'name' => 'themer.admin.themer.form.theme.txtelem.optn.h2' ),
						array( 'id' => '4', 'name' => 'themer.admin.themer.form.theme.txtelem.optn.h3' ),
						array( 'id' => '5', 'name' => 'themer.admin.themer.form.theme.txtelem.optn.h4' ),
						array( 'id' => '6', 'name' => 'themer.admin.themer.form.theme.txtelem.optn.h5' ),
						array( 'id' => '7', 'name' => 'themer.admin.themer.form.theme.txtelem.optn.h6' ),
				),
				'label'			=> 'themer.admin.themer.form.theme.label.textelem',
			),
		'txtelemoptn1'		=> array( 'order'	=> 210, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'txtelemgffont' => array(
				'order'			=> 212,
				'type'			=> 'webfont',
				'value'			=> '- use primary -',
				'validation'	=> '',
				'label'			=> 'themer.admin.themer.form.theme.label.textelemgffont',
				'nodesc'		=> true,
		),
		'txtelemgfsize' => array(
				'order'			=> 214,
				'type'			=> 'text',
				'size'			=> '4',
				'class'			=> 'span1',
				'value'			=> '13',
				'validation'	=> '',
				'label'			=> 'themer.admin.themer.form.theme.label.textelemgfsize',
				'description'	=> 'themer.admin.themer.form.theme.description.textelemgfsize'
		),
		'txtelemgfcolor' => array(
				'order'			=> 216,
				'type'			=> 'minicolors',
				'value'			=> '#333333',
				'nodesc'		=> true,
				'label'			=> 'themer.admin.themer.form.theme.label.txtelemgfcolor',
		),
		'txtelemoptn1c'		=> array( 'order'	=> 219, 'class'	=> 'well well-small', 'type'	=> 'wrapc' ),
		'txtelemoptn2'		=> array( 'order'	=> 220, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'txtelemh1font' => array(
				'order'			=> 222,
				'type'			=> 'webfont',
				'value'			=> '- use primary -',
				'validation'	=> '',
				'label'			=> 'themer.admin.themer.form.theme.label.textelemgffont',
				'nodesc'		=> true,
		),
		'txtelemh1size' => array(
				'order'			=> 224,
				'type'			=> 'text',
				'size'			=> '4',
				'class'			=> 'span1',
				'value'			=> '30',
				'validation'	=> '',
				'label'			=> 'themer.admin.themer.form.theme.label.textelemgfsize',
				'description'	=> 'themer.admin.themer.form.theme.description.textelemgfsize'
		),
		'txtelemh1color' => array(
				'order'			=> 226,
				'type'			=> 'minicolors',
				'value'			=> '#333333',
				'nodesc'		=> true,
				'label'			=> 'themer.admin.themer.form.theme.label.txtelemgfcolor',
		),
		'txtelemoptn2c'		=> array( 'order'	=> 229, 'class'	=> 'well well-small', 'type'	=> 'wrapc' ),
		'txtelemoptn3'		=> array( 'order'	=> 230, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'txtelemh2font' => array(
				'order'			=> 232,
				'type'			=> 'webfont',
				'value'			=> '- use primary -',
				'validation'	=> '',
				'label'			=> 'themer.admin.themer.form.theme.label.textelemgffont',
				'nodesc'		=> true,
		),
		'txtelemh2size' => array(
				'order'			=> 234,
				'type'			=> 'text',
				'size'			=> '4',
				'class'			=> 'span1',
				'value'			=> '24',
				'validation'	=> '',
				'label'			=> 'themer.admin.themer.form.theme.label.textelemgfsize',
				'description'	=> 'themer.admin.themer.form.theme.description.textelemgfsize'
		),
		'txtelemh2color' => array(
				'order'			=> 236,
				'type'			=> 'minicolors',
				'value'			=> '#333333',
				'nodesc'		=> true,
				'label'			=> 'themer.admin.themer.form.theme.label.txtelemgfcolor',
		),
		'txtelemoptn3c'		=> array( 'order'	=> 239, 'class'	=> 'well well-small', 'type'	=> 'wrapc' ),
		'txtelemoptn4'		=> array( 'order'	=> 240, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'txtelemh3font' => array(
				'order'			=> 242,
				'type'			=> 'webfont',
				'value'			=> '- use primary -',
				'validation'	=> '',
				'label'			=> 'themer.admin.themer.form.theme.label.textelemgffont',
				'nodesc'		=> true,
		),
		'txtelemh3size' => array(
				'order'			=> 244,
				'type'			=> 'text',
				'size'			=> '4',
				'class'			=> 'span1',
				'value'			=> '18',
				'validation'	=> '',
				'label'			=> 'themer.admin.themer.form.theme.label.textelemgfsize',
				'description'	=> 'themer.admin.themer.form.theme.description.textelemgfsize'
		),
		'txtelemh3color' => array(
				'order'			=> 246,
				'type'			=> 'minicolors',
				'value'			=> '#333333',
				'nodesc'		=> true,
				'label'			=> 'themer.admin.themer.form.theme.label.txtelemgfcolor',
		),
		'txtelemoptn4c'		=> array( 'order'	=> 249, 'class'	=> 'well well-small', 'type'	=> 'wrapc' ),
		'txtelemoptn5'		=> array( 'order'	=> 250, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'txtelemh4font' => array(
				'order'			=> 252,
				'type'			=> 'webfont',
				'value'			=> '- use primary -',
				'validation'	=> '',
				'label'			=> 'themer.admin.themer.form.theme.label.textelemgffont',
				'nodesc'		=> true,
		),
		'txtelemh4size' => array(
				'order'			=> 254,
				'type'			=> 'text',
				'size'			=> '4',
				'class'			=> 'span1',
				'value'			=> '14',
				'validation'	=> '',
				'label'			=> 'themer.admin.themer.form.theme.label.textelemgfsize',
				'description'	=> 'themer.admin.themer.form.theme.description.textelemgfsize'
		),
		'txtelemh4color' => array(
				'order'			=> 256,
				'type'			=> 'minicolors',
				'value'			=> '#333333',
				'nodesc'		=> true,
				'label'			=> 'themer.admin.themer.form.theme.label.txtelemgfcolor',
		),
		'txtelemoptn5c'		=> array( 'order'	=> 259, 'class'	=> 'well well-small', 'type'	=> 'wrapc' ),
		'txtelemoptn6'		=> array( 'order'	=> 260, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'txtelemh5font' => array(
				'order'			=> 262,
				'type'			=> 'webfont',
				'value'			=> '- use primary -',
				'validation'	=> '',
				'label'			=> 'themer.admin.themer.form.theme.label.textelemgffont',
				'nodesc'		=> true,
		),
		'txtelemh5size' => array(
				'order'			=> 264,
				'type'			=> 'text',
				'size'			=> '4',
				'class'			=> 'span1',
				'value'			=> '12',
				'validation'	=> '',
				'label'			=> 'themer.admin.themer.form.theme.label.textelemgfsize',
				'description'	=> 'themer.admin.themer.form.theme.description.textelemgfsize'
		),
		'txtelemh5color' => array(
				'order'			=> 266,
				'type'			=> 'minicolors',
				'value'			=> '#333333',
				'nodesc'		=> true,
				'label'			=> 'themer.admin.themer.form.theme.label.txtelemgfcolor',
		),
		'txtelemoptn6c'		=> array( 'order'	=> 269, 'class'	=> 'well well-small', 'type'	=> 'wrapc' ),
		'txtelemoptn7'		=> array( 'order'	=> 270, 'class'	=> 'well well-small', 'type'	=> 'wrapo' ),
		'txtelemh6font' => array(
				'order'			=> 272,
				'type'			=> 'webfont',
				'value'			=> '- use primary -',
				'validation'	=> '',
				'label'			=> 'themer.admin.themer.form.theme.label.textelemgffont',
				'nodesc'		=> true,
		),
		'txtelemh6size' => array(
				'order'			=> 274,
				'type'			=> 'text',
				'size'			=> '4',
				'class'			=> 'span1',
				'value'			=> '11',
				'validation'	=> '',
				'label'			=> 'themer.admin.themer.form.theme.label.textelemgfsize',
				'description'	=> 'themer.admin.themer.form.theme.description.textelemgfsize'
		),
		'txtelemh6color' => array(
				'order'			=> 276,
				'type'			=> 'minicolors',
				'value'			=> '#999999',
				'nodesc'		=> true,
				'label'			=> 'themer.admin.themer.form.theme.label.txtelemgfcolor',
		),
		'txtelemoptn7c'		=> array( 'order'	=> 279, 'class'	=> 'well well-small', 'type'	=> 'wrapc' ),
		);